### PR TITLE
Update Armory from upstream and Windows 10 fix

### PR DESCRIPTION
**Pull request by siraj**

### CODE REVIEW

**Comment by Ation** [comment]
Can you update your branch from upstream?
Diff should display only your changes

**Comment by pavel-kokolemin** [comment]
LGTM, no change in unit tests passing in terminal and PB.

**Comment by sergey-chernikov** [comment]
I guess we should merge upstream in a separate PR, and then rebase this PR?

**Comment by Ation** [comment]
I was confused by the title and didn't noticed that we don't have this commits

**Comment by pavel-kokolemin** [comment]
> I guess we should merge upstream in a separate PR, and then rebase this PR?

Looks like that's upstream merge itself.

**Comment by sergey-chernikov** [comment]
> Looks like that's upstream merge itself.

Not really - there was own commit

**Pull request merged**
